ctfFramework: CTFd 2.x
juiceShopUrl: https://juice-shop.herokuapp.com
ctfKey: YOUR-KEY-HERE
countryMapping: https://raw.githubusercontent.com/bkimminich/juice-shop/master/config/fbctf.yml # ignored for CTFd
insertHints: free
insertHintUrls: paid # optional for FBCTF
