#!/usr/bin/env bash

# Dependencies: Heroku CLI, juiceshop-ctf

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PREFIX=ctf
KEY=$(cat config.yml | awk '/ctfKey:/ {print $2}')
ENV=ctf
CTFD="https://bouvet-ctfd.herokuapp.com"

# TODO: Make keepalive-service (also on Herok?); see Dankenstein
# TODO: Port to Kubernetes? https://medium.com/@rkkautsar/how-docker-helps-me-manage-a-capture-the-flag-competition-7af303c1de2

case "$1" in
    config )
        OLD_DIR=$(pwd)
        cd $DIR

        sed -i.bak "/^[[:space:]]*ctfKey:/ s/:.*/: $(echo $RANDOM | md5)/" config.yml && rm config.yml.bak
        juice-shop-ctf --config config.yml


        cd $OLD_DIR
    ;;
    scoreboard )
        echo "Will now continuously ping scoreboard every 15 min. to keep dynos up until process is killed (ctrl+c)..."
        while [ 1 ]
        do
            TIME=$(date +"%T")
            echo "Pinged at $TIME"
            curl -L $CTFD >/dev/null 2>&1
            sleep 900
        done
        ;;
    start )
        if [[ -f $DIR/teams.txt ]]; then
            echo "Instances running! Stop current CTF before trying again"
            exit
        fi

        if [[ -z "$2" ]]; then
            echo "No number of instances given"
            exit
        fi

        OLD_DIR=$(pwd)
        cd $DIR

        git clone --depth 1 https://github.com/bkimminich/juice-shop.git > /dev/null 2>&1
        cd juice-shop
        rm -rf .git
        git init && git add -A && git commit -m "Init repo" > /dev/null 2>&1
        cd ..

        echo "Starting CTF..."
        heroku login
        mkdir deployment
        cd deployment
        echo "Using key $KEY"
        echo "You can now set up your CTFd instance"

        python2 $DIR/name_generator.py "$2" > $DIR/teams.txt
        while read p; do
            #echo "$p"
            cp -r ../juice-shop $p
            cd $p
            heroku create $PREFIX-$p
            heroku config:add CTF_KEY=$KEY NODE_ENV=$ENV
            git push heroku master
            cd ..
        done <$DIR/teams.txt

        cd $OLD_DIR
        ;;
    keepup )
        echo "Will now continuously ping scoreboard and each instance every 15 min. to keep dynos up until process is killed (ctrl+c)..."
        while [ 1 ]
        do
            TIME=$(date +"%T")
            echo "Pinged at $TIME"
            curl -L $CTFD >/dev/null 2>&1
            while read p; do
                curl -L https://$PREFIX-$p.herokuapp.com/ >/dev/null 2>&1
            done <$DIR/teams.txt
            sleep 900
        done
        ;;
    stop )
        echo "Stopping CTF..."
        OLD_DIR=$(pwd)
        cd $DIR/deployment
        while read p; do
            cd $p
            heroku apps:destroy $PREFIX-$p --confirm $PREFIX-$p
            cd ..
            rm -rf $p
        done <$DIR/teams.txt
        cd ..
        rm $DIR/teams.txt
        cd $OLD_DIR
        ;;
    * )
        echo "Arg $1 not recognized..."
        ;;
esac
